config/routes.rb
Rails.application.routes.draw do
  get 'main/index'

  resources :vehicles

  root 'main#index'




  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

end

app/models/vehicle.rb
class Vehicle < ApplicationRecord
  validates :plate_number, presence: true,
            length: { minimum: 7 }

  validates_format_of :matriculation_date, :with => /\d{2}\/\d{2}\/\d{4}/, :message => "^Date must be in the following format: dd/mm/yyyy"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
  end
end

app/controllers/vehicles_controller.rb
class VehiclesController < ApplicationController

  def new
    @vehicle = Vehicle.new
  end

  def index

  end


  def create
    @vehicle = Vehicle.new(vehicle_params)

    if @vehicle.save
      redirect_to @vehicle
    else
      render 'new'
    end
  end

  def show
    #Define array with last digits of the plate for each day
    matriz=[ [1, 2], [3, 4], [5, 6], [7, 8], [9, 0] ]
    #*************************************************
    #Display fields on screen
    @vehicle = Vehicle.find(params[:id])
    @title = @vehicle.plate_number[6,6]
    main_date = DateTime.parse(@vehicle.matriculation_date)
    @main_date_1 =main_date.strftime("The date is %d/%m/%y")
    @main_time = @vehicle.time.strftime("%H : %M")
    @main_day = main_date.strftime("%A")
    #***************************************
    #select day of week to find in the array
    day_week = main_date.strftime("%w")
    #****************************************
    # select the digits in the array
    position1=matriz[day_week.to_i-1][0]
    position2=matriz[day_week.to_i-1][1]
    #****************************************
    #Validates permissions
    if @title.to_i==position1 or @title.to_i==position2
      if (@vehicle.time.hour.between?(7,9) and @vehicle.time.min.between?(1,30)) or (@vehicle.time.hour.between?(16,19) and @vehicle.time.min.between?(1,30))
        @meesage_user="You can't drive"
      else
        @meesage_user="You can drive"
     end
    else
      @meesage_user="You can drive "
    end
    #*****************************************
  end



  private
  def vehicle_params
    params.require(:vehicle).permit(:plate_number, :matriculation_date, :time)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/vehicles_helper.rb
module VehiclesHelper

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Picoplaca</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/main/index.html.erb
<h1>PICO Y PLACA PREDICTOR</h1>

<%= link_to 'Verify authorization pico y placa', new_vehicle_path %>

app/views/vehicles/new.html.erb
<h1>New Vehicle</h1>



<%= form_for :vehicle, url: vehicles_path do |f| %>
    <% if @vehicle.errors.any? %>
        <div id="error_explanation">
          <h2>
            <%= pluralize(@vehicle.errors.count, "error") %> prohibited
            this vehicle from being saved:
          </h2>
          <ul>
            <% @vehicle.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>
  <p>
    <%= f.label :'license plate number' %><br><br>
    <%= f.text_field :plate_number, required: true, maxlength: 7, pattern: "[A-Z A-Z A-Z 0-9 0-9 0-9 0-9]{7,}",  class: 'h1' %>
    <%= f.label(:aapl, 'Format example : PBO4206') %>
  </p>
 
  <p>
    <%= f.label :'Date' %><br>
    <%= f.text_field :matriculation_date, placeholder:'dd/mm/yyyy', class: 'form-control datepicker' %>
  </p>

  <p>
    <%= f.label :Time %><br>
    <%= f.time_select :time, :default => Time.now%>
  </p>

  <p>
    <%= f.submit 'Verify' %>
  </p>
    <%= link_to 'Back', :back %>
<% end %>

app/views/vehicles/show.html.erb
<p>
  <strong>Last digit:</strong>
  <%= @title %>
</p>

<p>
  <strong>Date:</strong>
  <%= @main_date_1%>
</p>

<p>
  <strong>Time:</strong>
  <%= @main_time%>
</p>

<p>
  <strong>Weekday:</strong>
  <%= @main_day%>
</p>

<p>
  <strong>Message:</strong>
  <%= @meesage_user%>
</p>


<%= link_to 'Back', :back %>